# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: calculator.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'calculator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\",\n\x10OperationRequest\x12\x0b\n\x03opA\x18\x01 \x01(\x05\x12\x0b\n\x03opB\x18\x02 \x01(\x05\" \n\x11OperationResponse\x12\x0b\n\x03res\x18\x01 \x01(\x05\x32\xa9\x02\n\nCalculator\x12\x42\n\x03\x41\x64\x64\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12G\n\x08Subtract\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12G\n\x08Multiply\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponse\x12\x45\n\x06\x44ivide\x12\x1c.calculator.OperationRequest\x1a\x1d.calculator.OperationResponseB#\n\x0eit.ingsw.protoB\x0f\x43\x61lculatorProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'calculator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016it.ingsw.protoB\017CalculatorProtoP\001'
  _globals['_OPERATIONREQUEST']._serialized_start=32
  _globals['_OPERATIONREQUEST']._serialized_end=76
  _globals['_OPERATIONRESPONSE']._serialized_start=78
  _globals['_OPERATIONRESPONSE']._serialized_end=110
  _globals['_CALCULATOR']._serialized_start=113
  _globals['_CALCULATOR']._serialized_end=410
# @@protoc_insertion_point(module_scope)
