# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import rubrica_pb2 as rubrica__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in rubrica_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RubricaStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddContact = channel.unary_unary(
                '/rubrica.Rubrica/AddContact',
                request_serializer=rubrica__pb2.Person.SerializeToString,
                response_deserializer=rubrica__pb2.Result.FromString,
                _registered_method=True)
        self.GetContact = channel.unary_unary(
                '/rubrica.Rubrica/GetContact',
                request_serializer=rubrica__pb2.NomeContatto.SerializeToString,
                response_deserializer=rubrica__pb2.Person.FromString,
                _registered_method=True)
        self.GetAll = channel.unary_unary(
                '/rubrica.Rubrica/GetAll',
                request_serializer=rubrica__pb2.ListRequest.SerializeToString,
                response_deserializer=rubrica__pb2.ContactList.FromString,
                _registered_method=True)


class RubricaServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RubricaServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddContact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContact,
                    request_deserializer=rubrica__pb2.Person.FromString,
                    response_serializer=rubrica__pb2.Result.SerializeToString,
            ),
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=rubrica__pb2.NomeContatto.FromString,
                    response_serializer=rubrica__pb2.Person.SerializeToString,
            ),
            'GetAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAll,
                    request_deserializer=rubrica__pb2.ListRequest.FromString,
                    response_serializer=rubrica__pb2.ContactList.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rubrica.Rubrica', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rubrica.Rubrica', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Rubrica(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rubrica.Rubrica/AddContact',
            rubrica__pb2.Person.SerializeToString,
            rubrica__pb2.Result.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rubrica.Rubrica/GetContact',
            rubrica__pb2.NomeContatto.SerializeToString,
            rubrica__pb2.Person.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rubrica.Rubrica/GetAll',
            rubrica__pb2.ListRequest.SerializeToString,
            rubrica__pb2.ContactList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
