# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: rubrica.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'rubrica.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rrubrica.proto\x12\x07rubrica\"9\n\x06Person\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0f\n\x07\x63ognome\x18\x02 \x01(\t\x12\x10\n\x08telefono\x18\x03 \x01(\x05\"\x15\n\x06Result\x12\x0b\n\x03res\x18\x01 \x01(\x08\"-\n\x0cNomeContatto\x12\x0c\n\x04nome\x18\x01 \x01(\t\x12\x0f\n\x07\x63ognome\x18\x02 \x01(\t\"\r\n\x0bListRequest\"0\n\x0b\x43ontactList\x12!\n\x08\x63ontatti\x18\x01 \x03(\x0b\x32\x0f.rubrica.Person2\xa5\x01\n\x07Rubrica\x12.\n\nAddContact\x12\x0f.rubrica.Person\x1a\x0f.rubrica.Result\x12\x34\n\nGetContact\x12\x15.rubrica.NomeContatto\x1a\x0f.rubrica.Person\x12\x34\n\x06GetAll\x12\x14.rubrica.ListRequest\x1a\x14.rubrica.ContactListB \n\x0eit.ingsw.protoB\x0cRubricaProtoP\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'rubrica_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\016it.ingsw.protoB\014RubricaProtoP\001'
  _globals['_PERSON']._serialized_start=26
  _globals['_PERSON']._serialized_end=83
  _globals['_RESULT']._serialized_start=85
  _globals['_RESULT']._serialized_end=106
  _globals['_NOMECONTATTO']._serialized_start=108
  _globals['_NOMECONTATTO']._serialized_end=153
  _globals['_LISTREQUEST']._serialized_start=155
  _globals['_LISTREQUEST']._serialized_end=168
  _globals['_CONTACTLIST']._serialized_start=170
  _globals['_CONTACTLIST']._serialized_end=218
  _globals['_RUBRICA']._serialized_start=221
  _globals['_RUBRICA']._serialized_end=386
# @@protoc_insertion_point(module_scope)
